[project]
name = "generate-images"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
image-generation = [
    "datasets>=2.14.0",
    "image-generator[huggingface] @ git+https://github.com/paulovsantanas/image-generator.git",
    "pillow>=10.0.0",
    "tqdm>=4.64.0",
    "torch",
]
prompt-enhancing = [
    "accelerate",
    "torch",
    "torchvision",
    "transformers>=4.56.0,<5",
    "huggingface-hub",
    "qwen-vl-utils",
    "datasets>=2.14.0",
    "google-genai>=0.3.0",
    "requests>=2.28.0",
    "tiktoken",
    "tqdm>=4.64.0",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
